language: perl
sudo: false
perl:
  - "5.8"
  - "5.10"
  - "5.16"
  - "5.26"
install:
  - curl -sSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - prove -l t
